Fixed prepare statement to work with $ instead of ?
leocavalcante/swoole-postgresql-doctrine-driver pull request #1
Opened 2021-10-08 19:05 UTC by thomaspicquet

Doctrine prepare statements with `?` aren't supported by `swoole_postgres` and need to use `$n`

2021-10-08 19:21 UTC, leocavalcante requested changes

2021-10-08 19:21 UTC, leocavalcante commented on src/Connection.php
> +        } catch (\Excception $e) {
```suggestion
        } catch (\Exception $e) {
```

2021-10-08 19:21 UTC, leocavalcante commented on src/Driver.php
> +    public const DEFAULT_POOL_SIZE = 16;
Why?

2021-10-08 19:21 UTC, leocavalcante commented on src/Connection.php
> +            if (is_bool($result)) {
Should we check for `false`?

2021-10-09 16:16 UTC, deluxetom commented on src/Connection.php
> +            if (is_bool($result)) {
swoole postgres driver only takes a resource as the argument (fetchAssoc for example https://www.swoole.co.uk/docs/modules/swoole-coroutine-postgres-fetchAssoc)

2021-10-09 16:16 UTC, deluxetom commented on src/Driver.php
> +    public const DEFAULT_POOL_SIZE = 16;
that was a test, reverting

2021-10-11 13:11 UTC, leocavalcante commented on src/Connection.php
> +            throw \Doctrine\DBAL\Driver\PDO\Exception::new($e);
Not sure about throwing PDO's exceptions. It is not using PDO, it could be confusing.
I think it should have its own Exceptions, extending from `Doctrine\DBAL\Driver\AbstractException`. Its how other Drivers are doing.

2021-10-11 13:13 UTC, leocavalcante commented on src/Result.php
> +            throw new \Doctrine\DBAL\Exception('Result must be a resource');
What about throwing a `TypeError` instead? https://www.php.net/manual/en/class.typeerror.php

2021-10-12 04:21 UTC, deluxetom commented on src/Result.php
> +            throw new \Doctrine\DBAL\Exception('Result must be a resource');
Thanks for the review, I'll make the changes asap. Probably next weekend 😊

2021-12-28 17:26 UTC, leocavalcante commented
Hi @thomaspicquet 
Just was notified about a new commit at you branch.
Will you still work on this PR or we can close it by now?

2021-12-28 17:27 UTC, thomaspicquet commented
Erg sorry about that, totally forgot I had this PR opened, we can close it for now, I actually switched to openswoole on my end.
Would you like to start a new repo for openswoole?

2021-12-28 19:01 UTC, leocavalcante commented
That's ok. I actually haven't set one ext or another https://github.com/leocavalcante/swoole-postgresql-doctrine-driver/issues/3 it should work for both extensions by now.

2021-12-28 19:01 UTC, closed without merging